name: Prueba
on:
  push:
    branches:
    - main

jobs:
  Inicial:
    runs-on: ubuntu-latest

    steps:
    - name: Say something ðŸ’¡
      uses: actions/checkout@v2

    - name: mensaje
      if: ${{ github.ref == 'refs/heads/main'}}
      run: echo "hello"
